-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "gainOrLoss" DOUBLE PRECISION,
ADD COLUMN     "marketValue" DOUBLE PRECISION,
ADD COLUMN     "pruValue" DOUBLE PRECISION,
ADD COLUMN     "pvMvPercentage" DOUBLE PRECISION;
